apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:WnGZQMtgh01u4SEEs91LqA==,iv:CKmECcC6m2/ddL7/sbuFhyEdDPWOOtkV3n6L14+gMRs=,tag:XiwRROp42PhstsAMIMNGFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1awxc03edt5cvhd4tj0jurkk8cc2g9zp06m2xm5fglhn5dvnmqssq6rmjfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdnBjTk5ZblJ6bFJOQnlN
            WVYvMld1dzBpTmpuMGJ0KzI4WFo2S0tQRjNBClVFT0RackFQZzNLcTI5TVVwUzZm
            YmNneEtFY0RDM0xtcUd0ZWhxd29sLzQKLS0tIHVnRDFneCtVQWV4cUZ4K0U0cnBk
            a3lQb29GS1JlWm94cllVRjJHZm83aFkKk0RYooBEtbpKPEfprawJNWo9uudPbRpK
            RoMD0w244+jtCFzqnSgaUOmwrP3fieO3knRsiVKhXydIQZY1iWy3cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T19:04:41Z"
    mac: ENC[AES256_GCM,data:gtF52QJpGPWoTQVy7bOshYMRUJUm8VIU1DZIUMMO+aKyJaOHsPUIgbu6/sy5qFc0nWKZi2xEmmQcXMRkL2h7c+6cF/Qx09yLojzgGI+f3SyH0TM71ObDXbsXwsRl6wb6aCLKTyRVTPSr3OFVsaS3zjyDNVeCn2PpvVTRqGgPDqI=,iv:Z1MTHQBCETWxkQqEPkbCmmBGuA+B9PtOY+cAavXFplU=,tag:pUKmlylbXtvKtMqqgnCXlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
